#! /usr/bin/env bash
##############################################################################
#
# Copyright (C) Zenoss, Inc. 2008, 2012, all rights reserved.
#
# This content is made available according to terms specified in
# License.zenoss under the directory where your Zenoss product is installed.
#
##############################################################################

set -ex

MYPATH=`python -c "import os.path; print os.path.realpath('$0')"`
THISDIR=`dirname $MYPATH`
PRGHOME=`dirname $THISDIR`
PRGNAME=zenjmxnotificationlistener

LIB_DIR=${PRGHOME}/lib

CFGFILE=${ZENHOME}/etc/zenjmxnotificationlistener.conf
[ -f ${CFGFILE} ] || cp ${LIB_DIR}/zenjmxnotifications.conf ${CFGFILE}

MONITOR=`grep monitorName ${CFGFILE} | awk '{split($0,a,"="); print a[2]}'`
PIDFILE=${ZENHOME}/var/zenjmxnotifications-${MONITOR}.pid

CMD=$1
shift

. ${PRGHOME}/bin/java-functions.sh

cd ${LIB_DIR}
LOG4J_PROPS=`find . -name log4j.properties`
replace "@@ZENJMXNL_LOGFILE@@" \
    "${ZENHOME}/log/zenjmxnotificationlistener.log" \
    ${LOG4J_PROPS}

START_ARGS="-jar zenoss-jmx-notification-listener-0.0.1.jar --configfile ${CFGFILE} $@"
RUN_ARGS=$START_ARGS

generic $@
